import type { StoredAnalysis } from "./storage";

interface ObsidianExport {
  uri: string;
  filename: string;
}

export function exportToObsidian(analysis: StoredAnalysis): ObsidianExport {
  const date = analysis.date
    ? new Date(analysis.date).toISOString().split("T")[0]
    : new Date(analysis.timestamp).toISOString().split("T")[0];

  const safeName = (analysis.title || "Untitled")
    .replace(/[\/\\:*?"<>|]/g, "-")
    .substring(0, 80);

  const filename = `${date} - ${safeName}`;

  const content = buildNoteContent(analysis, date);

  // Obsidian URI scheme — opens Obsidian and creates the note
  // https://docs.obsidian.md/Advanced+URIs
  const params = new URLSearchParams({
    vault: "PhDVault",
    name: `Fieldwork/Omi Analysis/${filename}`,
    content,
    append: "false",
  });

  const uri = `obsidian://advanced-uri?${params.toString()}`;

  return { uri, filename };
}

export function exportAllToObsidian(analyses: StoredAnalysis[]): string[] {
  return analyses.map((a) => exportToObsidian(a).uri);
}

function buildNoteContent(analysis: StoredAnalysis, date: string): string {
  let md = `---
title: "${(analysis.title || "Untitled").replace(/"/g, '\\"')}"
date: ${date}
analyzed: ${analysis.timestamp}
category: ${analysis.category || "conversation"}
source: Omi DK2
tags:
  - omi-analysis
  - fieldwork
---

# ${analysis.title || "Untitled"}

> [!info] Analyzed on ${new Date(analysis.timestamp).toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })} from an Omi DK2 conversation recorded ${date}.

## 🎯 Thesis Relevance

${analysis.thesis_relevance}

## 🔍 Derived Meanings

${analysis.meanings}

## 📝 Summary

${analysis.summary}

## 🚀 Forward Thinking

${analysis.forward_thinking}
`;

  if (analysis.custom) {
    md += `
## ⚙️ Custom Analysis

> **Prompt:** ${analysis.custom.prompt}

${analysis.custom.result}
`;
  }

  md += `
---
*Generated by [[Omi Thesis Analyzer]] — Pioneer Sovereignty fieldwork analysis.*
`;

  return md;
}

export function downloadMarkdown(analysis: StoredAnalysis): void {
  const date = analysis.date
    ? new Date(analysis.date).toISOString().split("T")[0]
    : new Date(analysis.timestamp).toISOString().split("T")[0];

  const safeName = (analysis.title || "Untitled")
    .replace(/[\/\\:*?"<>|]/g, "-")
    .substring(0, 80);

  const content = buildNoteContent(analysis, date);
  const blob = new Blob([content], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${date} - ${safeName}.md`;
  a.click();
  URL.revokeObjectURL(url);
}
