import type { StoredAnalysis } from "./storage";

interface ObsidianExport {
  uri: string;
  filename: string;
}

function buildNoteContent(analysis: StoredAnalysis, date: string): string {
  let md = `---
title: "${(analysis.title || "Untitled").replace(/"/g, '\\"')}"
date: ${date}
analyzed: ${analysis.timestamp}
category: ${analysis.category || "conversation"}
source: Omi DK2
tags:
  - omi-analysis
  - fieldwork
  - pioneer-sovereignty
---

# ${analysis.title || "Untitled"}

> [!info] Analyzed on ${new Date(analysis.timestamp).toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })} from an Omi DK2 conversation recorded ${date}.

## 📜 RQ1 — Documentary Record

${analysis.rq1_documentary_record}

## 🏚️ RQ2 — Everyday Practices

${analysis.rq2_everyday_practices}

## 🪶 RQ3 — CSKT Intersection

${analysis.rq3_cskt_intersection}

## 🐎 RQ4 — Wildness Imaginary

${analysis.rq4_wildness_imaginary}

## 🎯 Orienting Conditions

${analysis.conditions_check}

## ⚖️ Rival Hypothesis Test

${analysis.rival_hypothesis_test}

## ❌ Refutation Signals

${analysis.refutation_signals}

## 🚀 Forward Thinking

${analysis.forward_thinking}
`;

  if (analysis.custom) {
    md += `
## ⚙️ Custom Analysis

> **Prompt:** ${analysis.custom.prompt}

${analysis.custom.result}
`;
  }

  md += `
---
*Generated by [[Omi Thesis Analyzer]] — Pioneer Sovereignty fieldwork analysis.*
`;

  return md;
}

export function exportToObsidian(analysis: StoredAnalysis): ObsidianExport {
  const date = analysis.date
    ? new Date(analysis.date).toISOString().split("T")[0]
    : new Date(analysis.timestamp).toISOString().split("T")[0];

  const safeName = (analysis.title || "Untitled")
    .replace(/[\/\\:*?"<>|]/g, "-")
    .substring(0, 80);

  const filename = `${date} - ${safeName}`;
  const content = buildNoteContent(analysis, date);

  const params = new URLSearchParams({
    vault: "PhDVault",
    name: `Fieldwork/Omi Analysis/${filename}`,
    content,
    append: "false",
  });

  const uri = `obsidian://advanced-uri?${params.toString()}`;
  return { uri, filename };
}

export function downloadMarkdown(analysis: StoredAnalysis): void {
  const date = analysis.date
    ? new Date(analysis.date).toISOString().split("T")[0]
    : new Date(analysis.timestamp).toISOString().split("T")[0];

  const safeName = (analysis.title || "Untitled")
    .replace(/[\/\\:*?"<>|]/g, "-")
    .substring(0, 80);

  const content = buildNoteContent(analysis, date);
  const blob = new Blob([content], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${date} - ${safeName}.md`;
  a.click();
  URL.revokeObjectURL(url);
}
