"use client";

export interface StoredAnalysis {
  id: string;
  conversationId: string;
  timestamp: string;
  title: string;
  category?: string;
  date?: string;
  thesis_relevance: string;
  meanings: string;
  summary: string;
  forward_thinking: string;
  custom?: {
    prompt: string;
    result: string;
    timestamp: string;
  };
}

const STORAGE_KEY = "omi-thesis-analyses";

export function getStoredAnalyses(): StoredAnalysis[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    return raw ? JSON.parse(raw) : [];
  } catch {
    return [];
  }
}

export function getStoredAnalysis(conversationId: string): StoredAnalysis | null {
  const all = getStoredAnalyses();
  return all.find((a) => a.conversationId === conversationId) || null;
}

export function saveAnalysis(analysis: Omit<StoredAnalysis, "id" | "timestamp">): StoredAnalysis {
  const all = getStoredAnalyses();
  const existing = all.findIndex((a) => a.conversationId === analysis.conversationId);

  const stored: StoredAnalysis = {
    ...analysis,
    id: crypto.randomUUID(),
    timestamp: new Date().toISOString(),
  };

  if (existing >= 0) {
    if (!stored.custom && all[existing].custom) {
      stored.custom = all[existing].custom;
    }
    stored.id = all[existing].id;
    all[existing] = stored;
  } else {
    all.unshift(stored);
  }

  localStorage.setItem(STORAGE_KEY, JSON.stringify(all));
  return stored;
}

export function saveCustomAnalysis(
  conversationId: string,
  custom: { prompt: string; result: string }
): void {
  const all = getStoredAnalyses();
  const existing = all.find((a) => a.conversationId === conversationId);
  if (existing) {
    existing.custom = { ...custom, timestamp: new Date().toISOString() };
    localStorage.setItem(STORAGE_KEY, JSON.stringify(all));
  }
}

export function deleteAnalysis(conversationId: string): void {
  const all = getStoredAnalyses().filter((a) => a.conversationId !== conversationId);
  localStorage.setItem(STORAGE_KEY, JSON.stringify(all));
}

export function getAnalyzedIds(): Set<string> {
  return new Set(getStoredAnalyses().map((a) => a.conversationId));
}

export function exportToMarkdown(analysis: StoredAnalysis): { markdown: string; filename: string } {
  const date = analysis.date
    ? new Date(analysis.date).toISOString().split("T")[0]
    : new Date(analysis.timestamp).toISOString().split("T")[0];

  const safeName = (analysis.title || "Untitled")
    .replace(/[\/\\:*?"<>|]/g, "-")
    .substring(0, 80);

  let md = `---
title: "${analysis.title || "Untitled"}"
date: ${date}
analyzed: ${analysis.timestamp}
category: ${analysis.category || "conversation"}
source: Omi DK2
tags:
  - omi-analysis
  - fieldwork
---

# ${analysis.title || "Untitled"}

> [!info] Analyzed on ${new Date(analysis.timestamp).toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })} from an Omi DK2 conversation recorded ${date}.

## 🎯 Thesis Relevance

${analysis.thesis_relevance}

## 🔍 Derived Meanings

${analysis.meanings}

## 📝 Summary

${analysis.summary}

## 🚀 Forward Thinking

${analysis.forward_thinking}
`;

  if (analysis.custom) {
    md += `
## ⚙️ Custom Analysis

> **Prompt:** ${analysis.custom.prompt}

${analysis.custom.result}
`;
  }

  md += `
---
*Generated by [[Omi Thesis Analyzer]] — Pioneer Sovereignty fieldwork analysis.*
`;

  return { markdown: md, filename: `${date} - ${safeName}.md` };
}
