"use client";

import { useEffect, useState, useCallback, Suspense } from "react";
import { useSearchParams } from "next/navigation";
import Link from "next/link";

interface ConvoRef {
  id: string;
  title: string;
  date: string;
  emoji: string;
}

interface GroupAnalysis {
  cross_conversation_themes: string;
  contradictions_and_tensions: string;
  evolution_and_patterns: string;
  synthesis: string;
  forward_thinking: string;
}

interface StoredGroupAnalysis {
  id: string;
  conversationIds: string[];
  conversations: ConvoRef[];
  timestamp: string;
  analysis: GroupAnalysis;
  custom?: { prompt: string; result: string; timestamp: string };
}

const STORAGE_KEY = "omi-thesis-group-analyses";

function getStoredGroupAnalyses(): StoredGroupAnalysis[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    return raw ? JSON.parse(raw) : [];
  } catch {
    return [];
  }
}

function saveGroupAnalysis(data: Omit<StoredGroupAnalysis, "id" | "timestamp">): StoredGroupAnalysis {
  const all = getStoredGroupAnalyses();
  const id = data.conversationIds.sort().join(",");
  const existing = all.findIndex((a) => a.conversationIds.sort().join(",") === id);

  const stored: StoredGroupAnalysis = {
    ...data,
    id: crypto.randomUUID(),
    timestamp: new Date().toISOString(),
  };

  if (existing >= 0) {
    if (!stored.custom && all[existing].custom) stored.custom = all[existing].custom;
    stored.id = all[existing].id;
    all[existing] = stored;
  } else {
    all.unshift(stored);
  }

  localStorage.setItem(STORAGE_KEY, JSON.stringify(all));
  return stored;
}

function saveGroupCustom(
  conversationIds: string[],
  custom: { prompt: string; result: string }
) {
  const all = getStoredGroupAnalyses();
  const key = conversationIds.sort().join(",");
  const existing = all.find((a) => a.conversationIds.sort().join(",") === key);
  if (existing) {
    existing.custom = { ...custom, timestamp: new Date().toISOString() };
    localStorage.setItem(STORAGE_KEY, JSON.stringify(all));
  }
}

function exportGroupToObsidian(stored: StoredGroupAnalysis): string {
  const dates = stored.conversations.map((c) => c.date.split("T")[0]);
  const dateRange = dates.length > 1 ? `${dates[0]} to ${dates[dates.length - 1]}` : dates[0];
  const titles = stored.conversations.map((c) => c.title).join(", ");
  const safeName = titles.replace(/[\/\\:*?"<>|]/g, "-").substring(0, 80);

  const convoLinks = stored.conversations
    .map((c) => {
      const d = c.date.split("T")[0];
      return `- [[${d} - ${c.title.replace(/[\/\\:*?"<>|]/g, "-")}]]`;
    })
    .join("\n");

  const md = `---
title: "Group Analysis: ${titles.replace(/"/g, '\\"').substring(0, 100)}"
date: ${dateRange}
analyzed: ${stored.timestamp}
type: group-analysis
source: Omi DK2
tags:
  - omi-analysis
  - fieldwork
  - group-analysis
  - pioneer-sovereignty
---

# Group Analysis

> [!info] ${stored.conversations.length} conversations analyzed together on ${new Date(stored.timestamp).toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}.

## Conversations in this group

${convoLinks}

## 🔗 Cross-Conversation Themes

${stored.analysis.cross_conversation_themes}

## ⚡ Contradictions & Tensions

${stored.analysis.contradictions_and_tensions}

## 📈 Evolution & Patterns

${stored.analysis.evolution_and_patterns}

## 🧩 Synthesis

${stored.analysis.synthesis}

## 🚀 Forward Thinking

${stored.analysis.forward_thinking}
${stored.custom ? `
## ⚙️ Custom Analysis

> **Prompt:** ${stored.custom.prompt}

${stored.custom.result}` : ""}
---
*Generated by [[Omi Thesis Analyzer]] — Pioneer Sovereignty fieldwork analysis.*
`;

  const params = new URLSearchParams({
    vault: "PhDVault",
    name: `Fieldwork/Omi Analysis/Group - ${safeName}`,
    content: md,
    append: "false",
  });

  return `obsidian://advanced-uri?${params.toString()}`;
}

function GroupAnalysisContent() {
  const searchParams = useSearchParams();
  const ids = searchParams.get("ids")?.split(",") || [];

  const [analysis, setAnalysis] = useState<GroupAnalysis | null>(null);
  const [conversations, setConversations] = useState<ConvoRef[]>([]);
  const [loading, setLoading] = useState(true);
  const [analyzing, setAnalyzing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [customPrompt, setCustomPrompt] = useState("");
  const [showCustom, setShowCustom] = useState(false);
  const [customAnalyzing, setCustomAnalyzing] = useState(false);
  const [exported, setExported] = useState(false);
  const [customResult, setCustomResult] = useState<string | null>(null);

  useEffect(() => {
    const stored = getStoredGroupAnalyses();
    const key = [...ids].sort().join(",");
    const existing = stored.find((a) => [...a.conversationIds].sort().join(",") === key);
    if (existing) {
      setAnalysis(existing.analysis);
      setConversations(existing.conversations);
      if (existing.custom) {
        setCustomPrompt(existing.custom.prompt);
        setCustomResult(existing.custom.result);
      }
      setLoading(false);
    } else {
      setLoading(false);
    }
  }, [ids]);

  const runAnalysis = useCallback(async () => {
    setAnalyzing(true);
    setError(null);
    try {
      const res = await fetch("/api/analyze-group", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ conversationIds: ids }),
      });
      const data = await res.json();
      if (data.error) setError(data.error);
      else {
        setAnalysis(data.analysis);
        setConversations(data.conversations);
        saveGroupAnalysis({
          conversationIds: ids,
          conversations: data.conversations,
          analysis: data.analysis,
        });
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : "Analysis failed");
    } finally {
      setAnalyzing(false);
    }
  }, [ids]);

  const runCustom = useCallback(async () => {
    if (!customPrompt.trim()) return;
    setCustomAnalyzing(true);
    setError(null);
    try {
      const res = await fetch("/api/analyze-group/custom", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ conversationIds: ids, prompt: customPrompt }),
      });
      const data = await res.json();
      if (data.error) setError(data.error);
      else {
        saveGroupCustom(ids, { prompt: customPrompt, result: data.result });
        setCustomResult(data.result);
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : "Custom analysis failed");
    } finally {
      setCustomAnalyzing(false);
    }
  }, [ids, customPrompt]);

  const handleExportObsidian = () => {
    const stored = getStoredGroupAnalyses();
    const key = [...ids].sort().join(",");
    const existing = stored.find((a) => [...a.conversationIds].sort().join(",") === key);
    if (existing) {
      const uri = exportGroupToObsidian(existing);
      window.open(uri, "_blank");
      setExported(true);
      setTimeout(() => setExported(false), 2000);
    }
  };

  const sections = analysis
    ? [
        { icon: "🔗", title: "Cross-Conversation Themes", subtitle: "Recurring ideas and shared concerns", content: analysis.cross_conversation_themes },
        { icon: "⚡", title: "Contradictions & Tensions", subtitle: "Where conversations diverge or conflict", content: analysis.contradictions_and_tensions },
        { icon: "📈", title: "Evolution & Patterns", subtitle: "How ideas change over time", content: analysis.evolution_and_patterns },
        { icon: "🧩", title: "Synthesis", subtitle: "The bigger picture across all conversations", content: analysis.synthesis },
        { icon: "🚀", title: "Forward Thinking", subtitle: "Research directions from cross-conversation patterns", content: analysis.forward_thinking },
      ]
    : [];

  return (
    <main className="max-w-3xl mx-auto px-4 py-8">
      <Link href="/" className="text-slate-400 hover:text-white text-sm mb-6 inline-flex items-center gap-1 min-h-[44px] py-2">
        ← Back to conversations
      </Link>

      <header className="mb-6">
        <h1 className="text-2xl font-bold text-white mb-2">
          <span aria-hidden="true">🧠</span> Group Analysis
        </h1>
        <p className="text-slate-400 text-sm">
          {ids.length} conversations selected for cross-conversation analysis
        </p>
        {conversations.length > 0 && (
          <div className="flex flex-wrap gap-2 mt-3" role="list" aria-label="Conversations in this group">
            {conversations.map((c) => (
              <span key={c.id} className="text-sm bg-slate-800 text-slate-300 px-3 py-1.5 rounded-md" role="listitem">
                <span aria-hidden="true">{c.emoji}</span> {c.title}
              </span>
            ))}
          </div>
        )}
      </header>

      {loading && (
        <div className="space-y-4" role="status" aria-label="Loading group analysis">
          <div className="skeleton h-8 w-3/4" />
          <div className="skeleton h-4 w-1/2" />
          <div className="skeleton h-32 w-full" />
          <div className="skeleton h-32 w-full" />
        </div>
      )}

      {error && (
        <div className="card p-6 border-red-500/50 mb-6" role="alert">
          <p className="text-red-400">⚠ {error}</p>
          <button
            onClick={() => setError(null)}
            className="mt-2 text-sm text-slate-400 hover:text-white min-h-[44px] px-2"
            aria-label="Dismiss error"
          >
            Dismiss
          </button>
        </div>
      )}

      {/* Analyze button */}
      {!analysis && !loading && (
        <button
          onClick={runAnalysis}
          disabled={analyzing}
          aria-label={`Run group analysis on ${ids.length} conversations`}
          className="w-full card p-6 text-center hover:border-indigo-500/50 transition-colors cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed mb-8 min-h-[44px]"
        >
          {analyzing ? (
            <div className="flex items-center justify-center gap-3">
              <span className="pulse-dot text-2xl" aria-hidden="true">⏳</span>
              <div>
                <p className="font-semibold text-white">Analyzing {ids.length} conversations...</p>
                <p className="text-slate-400 text-sm mt-1">Running cross-conversation analysis</p>
              </div>
            </div>
          ) : (
            <div>
              <p className="text-2xl mb-2" aria-hidden="true">🧠</p>
              <p className="font-semibold text-white">Run Group Analysis</p>
              <p className="text-slate-400 text-sm mt-1">Find patterns across {ids.length} conversations</p>
            </div>
          )}
        </button>
      )}

      {/* Analysis results */}
      {sections.length > 0 && (
        <section className="mb-8" aria-label="Cross-conversation analysis results">
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-xl font-bold text-white flex items-center gap-2">
              🧠 Cross-Conversation Analysis
              <span className="text-xs bg-indigo-900/50 text-indigo-200 px-2 py-0.5 rounded-full font-normal">saved</span>
            </h2>
            <div className="flex items-center gap-2">
              <button
                onClick={handleExportObsidian}
                aria-label="Export group analysis to Obsidian vault"
                className="text-sm bg-purple-900/40 hover:bg-purple-800/50 text-purple-200 px-3 py-2 min-h-[44px] rounded-lg transition-colors"
              >
                {exported ? "✓ Saved" : "📓 Send to Obsidian"}
              </button>
              <button
                onClick={runAnalysis}
                disabled={analyzing}
                aria-label="Re-run group analysis"
                className="text-sm text-slate-400 hover:text-indigo-400 transition-colors px-2 py-2 min-h-[44px]"
              >
                🔄
              </button>
            </div>
          </div>
          <div className="space-y-6">
            {sections.map((section) => (
              <div key={section.title} className="card p-6">
                <div className="analysis-section">
                  <h3><span aria-hidden="true">{section.icon}</span> {section.title}</h3>
                  <p className="text-xs text-slate-500 mb-3">{section.subtitle}</p>
                  <div className="whitespace-pre-wrap text-sm leading-relaxed">{section.content}</div>
                </div>
              </div>
            ))}
          </div>
        </section>
      )}

      {/* Custom group analysis */}
      <section className="mb-8" aria-label="Custom group analysis">
        <button
          onClick={() => setShowCustom(!showCustom)}
          aria-expanded={showCustom}
          aria-controls="custom-group-panel"
          className="w-full card p-5 text-left hover:border-amber-500/50 transition-colors cursor-pointer flex items-center justify-between min-h-[44px]"
        >
          <div className="flex items-center gap-3">
            <span className="text-xl" aria-hidden="true">⚙️</span>
            <div>
              <p className="font-semibold text-white">Custom Group Analysis</p>
              <p className="text-slate-500 text-sm">Ask a question across all selected conversations</p>
            </div>
          </div>
          <svg className={`w-5 h-5 text-slate-500 transition-transform ${showCustom ? "rotate-180" : ""}`} fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
          </svg>
        </button>

        {showCustom && (
          <div id="custom-group-panel" className="card mt-2 p-6 border-amber-500/30">
            <label className="block mb-3">
              <span className="text-sm font-medium text-slate-300 mb-2 block">What do you want to explore across these conversations?</span>
              <textarea
                value={customPrompt}
                onChange={(e) => setCustomPrompt(e.target.value)}
                placeholder="e.g., How do different speakers frame land ownership? What shared assumptions about 'the good life' emerge?"
                aria-label="Custom group analysis question"
                className="w-full bg-slate-900 border border-slate-700 rounded-lg p-3 text-sm text-slate-200 placeholder-slate-600 focus:border-amber-500 focus:outline-none resize-none"
                rows={3}
              />
            </label>
            <div className="flex flex-wrap gap-2 mb-3" role="group" aria-label="Quick prompt suggestions">
              {[
                "How do speakers frame land ownership differently?",
                "What shared assumptions about 'the good life' emerge?",
                "Where does resistance to outside authority appear?",
                "What role does family legacy play across conversations?",
              ].map((p) => (
                <button
                  key={p}
                  onClick={() => setCustomPrompt(p)}
                  aria-label={`Use prompt: ${p}`}
                  className="text-sm bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white px-3 py-2 min-h-[44px] rounded-md transition-colors"
                >
                  {p}
                </button>
              ))}
            </div>
            <button
              onClick={runCustom}
              disabled={customAnalyzing || !customPrompt.trim()}
              aria-label="Run custom group analysis"
              className="bg-amber-600 hover:bg-amber-500 disabled:bg-slate-700 disabled:text-white text-white font-medium py-2 px-5 min-h-[44px] rounded-lg text-sm transition-colors"
            >
              {customAnalyzing ? "⏳ Analyzing..." : "Run Custom Group Analysis"}
            </button>
          </div>
        )}

        {customResult && (
          <div className="card mt-2 p-6 border-amber-500/30">
            <div className="analysis-section" style={{ background: "rgba(245, 158, 11, 0.06)" }}>
              <h3 style={{ color: "#fbbf24" }}>
                <span aria-hidden="true">⚙️</span> Custom Group Analysis
              </h3>
              <p className="text-xs text-slate-500 mb-1">Prompt: &ldquo;{customPrompt}&rdquo;</p>
              <div className="whitespace-pre-wrap text-sm leading-relaxed mt-3">{customResult}</div>
            </div>
          </div>
        )}
      </section>
    </main>
  );
}

export default function GroupAnalysisPage() {
  return (
    <Suspense
      fallback={
        <div className="max-w-3xl mx-auto px-4 py-8" role="status" aria-label="Loading">
          <div className="space-y-4">
            <div className="skeleton h-8 w-3/4" />
            <div className="skeleton h-4 w-1/2" />
            <div className="skeleton h-32 w-full" />
          </div>
        </div>
      }
    >
      <GroupAnalysisContent />
    </Suspense>
  );
}
